### ISSUE TITLE
Rebuild Dockerfile to consider latest version of MusicBot 0.4.0

### ISSUE THREAD

**Issue by mohaidoss** [alexandreteles/jmusicbot-docker#13]
Hi,

Just a kind reminder that there is a new release of [jagrosh/MusicBot 0.4.0](https://github.com/jagrosh/MusicBot/releases/latest)

When you have time, can you please rebuild/push the images ?
Appreciate it :D

**Comment by martinbndr** [comment]
Indeed, that would be nice.  Also many thanks that you provide this image, works fine 👍

**Comment by alexandreteles** [comment]
That should be working now. Please test and let me know in a new issue if it's not.

**Comment by mohaidoss** [comment]
Well that's awkward... The new version 0.4.0 is bugged see https://github.com/jagrosh/MusicBot/issues/1537 .

Anyway, thanks for the update @alexandreteles 🤣
