### ISSUE TITLE
Consider using config folder instead of separate files

### ISSUE THREAD

**Issue by LunNova** [alexandreteles/jmusicbot-docker#4]
Symlinking the various config files into a single folder which can be mounted makes it easier to use a single volume for config.

Docker swarm users also can only mount folders.

**Comment by alexandreteles** [comment]
I don't use docker volumes or docker swarm for this deployment, so I guess that would be a lil bit out of scope and potentially force people to change their current configurations when updating to newer versions of the image, but I'll take it into consideration and see what can I do.
